# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aquacontrol.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61quacontrol.proto\x12\x08\x41quaCtrl\";\n\x10\x43ontrolRelayData\x12\x0f\n\x07\x63hannel\x18\x01 \x02(\r\x12\x16\n\x0estatus_control\x18\x02 \x02(\r\"\xa2\x01\n\x0bMonitorData\x12\x10\n\x08\x64\x65viceId\x18\x01 \x02(\r\x12\x18\n\x10\x41mpeChannel1x100\x18\x02 \x02(\r\x12\x0f\n\x07Oxyx100\x18\x03 \x02(\r\x12\x0e\n\x06pHx100\x18\x04 \x02(\r\x12\x13\n\x0bVoltagex100\x18\x05 \x02(\r\x12\x17\n\x0fTemperaturex100\x18\x06 \x02(\r\x12\x18\n\x10IsPowerLostPhare\x18\x07 \x02(\r\"\xcf\x01\n\x11\x43ontrolStatusData\x12\x11\n\tgatewayId\x18\x01 \x02(\r\x12\x18\n\x10\x41mpeChannel1x100\x18\x02 \x02(\r\x12\x18\n\x10\x41mpeChannel2x100\x18\x03 \x02(\r\x12\x18\n\x10IsPowerLostPhare\x18\x04 \x02(\r\x12\x16\n\x0eIsLostElectric\x18\x05 \x02(\r\x12\x17\n\x0fTemperaturex100\x18\x06 \x02(\r\x12\x13\n\x0bVoltagex100\x18\x07 \x02(\r\x12\x13\n\x0brelayStatus\x18\x08 \x01(\r')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aquacontrol_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONTROLRELAYDATA']._serialized_start=31
  _globals['_CONTROLRELAYDATA']._serialized_end=90
  _globals['_MONITORDATA']._serialized_start=93
  _globals['_MONITORDATA']._serialized_end=255
  _globals['_CONTROLSTATUSDATA']._serialized_start=258
  _globals['_CONTROLSTATUSDATA']._serialized_end=465
# @@protoc_insertion_point(module_scope)
