/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_AQUACTRL_AQUACONTROL_PB_H_INCLUDED
#define PB_AQUACTRL_AQUACONTROL_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* =========================================================
 1. LỆNH ĐIỀU KHIỂN (App -> Control)
 Dùng để bật/tắt 6 cái Relay trên mạch Control
 ========================================================= */
typedef struct _AquaCtrl_ControlRelayData {
    uint32_t channel;
    uint32_t status_control;
} AquaCtrl_ControlRelayData;

/* =========================================================
 2. DỮ LIỆU TỪ MẠCH MONITOR (Monitor -> Control -> App)
 Chứa đầy đủ các sensor đo đạc chuyên sâu
 ========================================================= */
typedef struct _AquaCtrl_MonitorData {
    uint32_t deviceId; /* ID của con Monitor (1, 2, 3...) */
    uint32_t AmpeChannel1x100;
    uint32_t Oxyx100;
    uint32_t pHx100;
    uint32_t Voltagex100;
    uint32_t Temperaturex100;
    uint32_t IsPowerLostPhare; /* Mất pha phía monitor (Bitmask từ 0 đến 7) */
} AquaCtrl_MonitorData;

/* =========================================================
 3. DỮ LIỆU TỪ MẠCH CONTROL (Control -> App)
 Báo cáo trạng thái của chính con Gateway (Con Cha)
 ========================================================= */
typedef struct _AquaCtrl_ControlStatusData {
    uint32_t gatewayId; /* ID của con Cha (Ao số mấy) */
    uint32_t AmpeChannel1x100;
    uint32_t AmpeChannel2x100;
    uint32_t IsPowerLostPhare;
    uint32_t IsLostElectric;
    uint32_t Temperaturex100;
    uint32_t Voltagex100;
    bool has_relayStatus;
    uint32_t relayStatus; /* Bitmask trạng thái 6 Relay */
} AquaCtrl_ControlStatusData;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AquaCtrl_ControlRelayData_init_default   {0, 0}
#define AquaCtrl_MonitorData_init_default        {0, 0, 0, 0, 0, 0, 0}
#define AquaCtrl_ControlStatusData_init_default  {0, 0, 0, 0, 0, 0, 0, false, 0}
#define AquaCtrl_ControlRelayData_init_zero      {0, 0}
#define AquaCtrl_MonitorData_init_zero           {0, 0, 0, 0, 0, 0, 0}
#define AquaCtrl_ControlStatusData_init_zero     {0, 0, 0, 0, 0, 0, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define AquaCtrl_ControlRelayData_channel_tag    1
#define AquaCtrl_ControlRelayData_status_control_tag 2
#define AquaCtrl_MonitorData_deviceId_tag        1
#define AquaCtrl_MonitorData_AmpeChannel1x100_tag 2
#define AquaCtrl_MonitorData_Oxyx100_tag         3
#define AquaCtrl_MonitorData_pHx100_tag          4
#define AquaCtrl_MonitorData_Voltagex100_tag     5
#define AquaCtrl_MonitorData_Temperaturex100_tag 6
#define AquaCtrl_MonitorData_IsPowerLostPhare_tag 7
#define AquaCtrl_ControlStatusData_gatewayId_tag 1
#define AquaCtrl_ControlStatusData_AmpeChannel1x100_tag 2
#define AquaCtrl_ControlStatusData_AmpeChannel2x100_tag 3
#define AquaCtrl_ControlStatusData_IsPowerLostPhare_tag 4
#define AquaCtrl_ControlStatusData_IsLostElectric_tag 5
#define AquaCtrl_ControlStatusData_Temperaturex100_tag 6
#define AquaCtrl_ControlStatusData_Voltagex100_tag 7
#define AquaCtrl_ControlStatusData_relayStatus_tag 8

/* Struct field encoding specification for nanopb */
#define AquaCtrl_ControlRelayData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   channel,           1) \
X(a, STATIC,   REQUIRED, UINT32,   status_control,    2)
#define AquaCtrl_ControlRelayData_CALLBACK NULL
#define AquaCtrl_ControlRelayData_DEFAULT NULL

#define AquaCtrl_MonitorData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   deviceId,          1) \
X(a, STATIC,   REQUIRED, UINT32,   AmpeChannel1x100,   2) \
X(a, STATIC,   REQUIRED, UINT32,   Oxyx100,           3) \
X(a, STATIC,   REQUIRED, UINT32,   pHx100,            4) \
X(a, STATIC,   REQUIRED, UINT32,   Voltagex100,       5) \
X(a, STATIC,   REQUIRED, UINT32,   Temperaturex100,   6) \
X(a, STATIC,   REQUIRED, UINT32,   IsPowerLostPhare,   7)
#define AquaCtrl_MonitorData_CALLBACK NULL
#define AquaCtrl_MonitorData_DEFAULT NULL

#define AquaCtrl_ControlStatusData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   gatewayId,         1) \
X(a, STATIC,   REQUIRED, UINT32,   AmpeChannel1x100,   2) \
X(a, STATIC,   REQUIRED, UINT32,   AmpeChannel2x100,   3) \
X(a, STATIC,   REQUIRED, UINT32,   IsPowerLostPhare,   4) \
X(a, STATIC,   REQUIRED, UINT32,   IsLostElectric,    5) \
X(a, STATIC,   REQUIRED, UINT32,   Temperaturex100,   6) \
X(a, STATIC,   REQUIRED, UINT32,   Voltagex100,       7) \
X(a, STATIC,   OPTIONAL, UINT32,   relayStatus,       8)
#define AquaCtrl_ControlStatusData_CALLBACK NULL
#define AquaCtrl_ControlStatusData_DEFAULT NULL

extern const pb_msgdesc_t AquaCtrl_ControlRelayData_msg;
extern const pb_msgdesc_t AquaCtrl_MonitorData_msg;
extern const pb_msgdesc_t AquaCtrl_ControlStatusData_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AquaCtrl_ControlRelayData_fields &AquaCtrl_ControlRelayData_msg
#define AquaCtrl_MonitorData_fields &AquaCtrl_MonitorData_msg
#define AquaCtrl_ControlStatusData_fields &AquaCtrl_ControlStatusData_msg

/* Maximum encoded size of messages (where known) */
#define AQUACTRL_AQUACONTROL_PB_H_MAX_SIZE       AquaCtrl_ControlStatusData_size
#define AquaCtrl_ControlRelayData_size           12
#define AquaCtrl_ControlStatusData_size          48
#define AquaCtrl_MonitorData_size                42

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
