/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "aquacontrol.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AquaCtrl_ControlRelayData, AquaCtrl_ControlRelayData, AUTO)


PB_BIND(AquaCtrl_MonitorData, AquaCtrl_MonitorData, AUTO)


PB_BIND(AquaCtrl_ControlStatusData, AquaCtrl_ControlStatusData, AUTO)
